apiVersion: v1
kind: Service
metadata:
  name: url-jarvis
  namespace: jarvis
  labels:
    app: url-jarvis
spec:
  type: ClusterIP
  selector:
    app: url-jarvis
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
